!function (app) {
  'use strict';
  
  app.constant('CARDS', {
    /*
     *
     * WHITE CARDS
     * Philly
     *
     */
     "#PhillyProbz.": "Philly",
     "Philadelphia.": "Philly",
     "West Philadelphia.": "Philly",
     "North Philadelphia.": "Philly",
     "Northeast Philadelphia.": "Philly",
     "The suburbs.": "Philly",
     "Wet Stuff.": "Philly",
     "The Philadelphia Parking Authority.": "Philly",
     "Node.js Meetup.": "Philly",
     "Ecstasy.": "Philly",
     "Temple University.": "Philly",
     "Foxes?": "Philly",
     "Cheeseteaks.": "Philly",
     "Hoagies.": "Philly",
     "Gyros.": "Philly",
     "Chipotle.": "Philly",
     "Comcast.": "Philly",
     "Slow internet speeds.": "Philly",
     "Kabletown.": "Philly",
     "Liberty Bell.": "Philly",
     "The lack of Apple Stores.": "Philly",
     "The shore to the east.": "Philly",
     "It's Always Sunny in Philadelphia.": "Philly",
     "Sand.": "Philly",
     "Independence Hall.": "Philly",
     "N3RD Street.": "Philly",
     "Pussy.": "Philly",
     "Fat People.": "Philly",
     "The University of Pennsylvania.": "Philly",
     "Not Penn State.": "Philly",
     "Brotherly Love.": "Philly",
     "The gays.": "Philly",
     "A river I can't pronounce.": "Philly",
     "First Bank of the United States.": "Philly",
     "Wawa.": "Philly",
     "World War Z.": "Philly",
     "A lack of funding.": "Philly",
     "Huge tall buildings.": "Philly",
     "Comcast's second erection.": "Philly",
     "Stray cats.": "Philly",
     "Homeless men.": "Philly",
     "Excessive homelessness.": "Philly",
     "Women in tech.": "Philly",
     "Mayor Nutter.": "Philly",
     "Mayor Nutter's Dog.": "Philly",
     "Mayor Nutter's Nuts.": "Philly",
     "SEPTA.": "Philly",
     "The Wrath of SEPTA.": "Philly",
     "The Market Frankford Line.": "Philly",
     "The West Trenton Line.": "Philly",
     "Suburban Station.": "Philly",
     "A train station with colorful tiles.": "Philly",
     "AT&T Stadium.": "Philly",
     "This meetup.": "Philly",
     "Chinatown.": "Philly",
     "Parking spaces.": "Philly",
     "The city across the river.": "Philly",
     "Sourdough bread.": "Philly",
     "Priests.": "Philly",
     "The Black Israelites.": "Philly",
     "Safe disappointment.": "Philly",
     "The school district.": "Philly",
     "Kimmel Center.": "Philly",
     "A pile of shock.": "Philly",
     "The rich person formerly known as Kobe Bryant.": "Philly",
     "Trust related issues.": "Philly",
     "The lack of a viable competitor.": "Philly",
     "The feels.": "Philly",
     "Taking SEPTA to school.": "Philly",
     "Street nudity.": "Philly",
     "The murals.": "Philly",
     "A William Penn sighting.": "Philly",
     "FUSAM scribbled on a wall.": "Philly",
     "William Penn rolling in his grave.": "Philly",
     "The Constitution.": "Philly",
     "First amendment rights.": "Philly",
     "Gun violence.": "Philly",
     "Bike thieves.": "Philly",
     "The poverty rate.": "Philly",
     "Obama's Visit.": "Philly",
     "A porta-potty tipping over.": "Philly",
     "Teenagers.": "Philly",
     "Roselike hardcore kids.": "Philly",
     "Stopping in West Philly for Lobster.": "Philly",
     "Paul Ryan.": "Philly",
     "Pork Rinds.": "Philly",
     "Bacon fries.": "Philly",
     "Wit whiz.": "Philly",
     "Wit-out whiz.": "Philly",
     "A balanced breakfast.": "Base",
     "Tweeting.": "Base",
     "The Big Bang.": "Base",
     "Fear itself.": "Base",
     "Science.": "Base",
     "Bling.": "Base",
     "The South.": "Base",
     "Global warming.": "Base",
     "Emotions.": "Base",
     "Cookie Monster devouring the Eucharist wafers.": "Base",
     "Dick Cheney.": "Base",
     "Yeast.": "Base",
     "Natural selection.": "Base",
     "Twinkies®.": "Base",
     "A LAN party.": "Base",
     "Five-Dollar Footlongs™.": "Base",
     "Preteens.": "Base",
     "A tiny horse.": "Base",
     "Authentic Mexican cuisine.": "Base",
     "Oversized lollipops.": "Base",
     "RoboCop.": "Base",
     "All-you-can-eat shrimp for $4.99.": "Base",
     "Britney Spears at 55.": "Base",
     "Ronald Reagan.": "Base",
     "Hot Pockets®.": "Base",
     "The World of Warcraft.": "Base",
     "God.": "Base",
     "Intelligent design.": "Base",
     "Domino's™ Oreo™ Dessert Pizza.": "Base",
     "Free samples.": "Base",
     "Douchebags on their iPhones.": "Base",
     "Hurricane Katrina.": "Base",
     "Republicans.": "Base",
     "The glass ceiling.": "Base",
     "Michelle Obama's arms.": "Base",
     "Bill Nye the Science Guy.": "Base",
     "Italians.": "Base",
     "Kim Jong-il.": "Base",
     "GoGurt®.": "Base",
     "Judge Judy.": "Base",
     "Judy": "Base",
     "Barack Obama.": "Base",
     "A disappointing birthday party.": "Base",
     "Obesity.": "Base",
     "BATMAN!!!": "Base",
     "The Trail of Tears.": "Base",
     "Ghosts.": "Base",
     "Bananas in Pajamas.": "Base",
     "The Make-A-Wish® Foundation.": "Base",
     /*
      *
      * WHITE CARDS
      * Pax
      *
      */
     "Loading from a previous save.": "Pax",
     "Punching a tree to gather wood.": "Pax",
     "Sharpening a foam broadsword on a foam whetstone.": "Pax",
     "Spending the year's insulin budget on Warhammer 40k figurines.": "Pax",
     "The depression that ensues after catching 'em all.": "Pax",
     "The rocket launcher.": "Pax",
     "Violating the First Law of Robotics.": "Pax",
     "An immediately regrettable $9 hot dog from the Boston Convention Center.": "Pax",
     "Casting Magic Missile at a bully.": "Pax",
     "Firefly: Season 2.": "Pax",
     "Paying the iron price.": "Pax",
     "Rotating shapes in mid-air so that they fit into other shapes when they fall.": "Pax",
     "Running out of stamina.": "Pax",
     "Achieving 500 actions per minute.": "Pax",
     "Charging up all the way.": "Pax",
     "Forgetting to eat, and consequently dying.": "Pax",
     "Smashing all the pottery in a Pottery Barn in search of rupees.": "Pax",
     "Wil Wheaton crashing an actual spaceship.": "Pax",
     /*
      *
      * WHITE CARDS
      * Expansion II
      *
      */
     "A low standard of living.": "Expansion II",
     "Panty raids.": "Expansion II",
     "A passionate Latino lover.": "Expansion II",
     "A rival dojo.": "Expansion II",
     "A web of lies.": "Expansion II",
     "Clams.": "Expansion II",
     "Apologizing.": "Expansion II",
     "Neil Patrick Harris.": "Expansion II",
     "Being a dinosaur.": "Expansion II",
     "Dorito breath.": "Expansion II",
     "Fabricating statistics.": "Expansion II",
     "Finding a skeleton.": "Expansion II",
     "Gandalf.": "Expansion II",
     "Genetically engineered super-soldiers.": "Expansion II",
     "Getting abducted by Peter Pan.": "Expansion II",
     "Good grammar.": "Expansion II",
     "Hipsters.": "Expansion II",
     "Literally eating shit.": "Expansion II",
     "Media coverage.": "Expansion II",
     "Medieval Times® Dinner & Tournament.": "Expansion II",
     "One thousand Slim Jims.": "Expansion II",
     "Ominous background music.": "Expansion II",
     "Overpowering your father.": "Expansion II",
     "Ryan Gosling riding in on a white horse.": "Expansion II",
     "Santa Claus.": "Expansion II",
     "Slow motion.": "Expansion II",
     "Space muffins.": "Expansion II",
     "The economy.": "Expansion II",
     "The harsh light of day.": "Expansion II",
     "The hiccups.": "Expansion II",
     "Being a busy adult with many important things to do.": "Expansion II",
     "Words, words, words.": "Expansion II",
    /*
     *
     * BLACK CARDS
     * Base
     *
     */
    "_? There's an app for that.": "Base",
    "Why can't I sleep at night?": "Base",
    "What's that smell?": "Base",
    "I got 99 problems but _ ain't one.": "Base",
    "Maybe she's born with it. Maybe it's _.": "Base",
    "What's the next Happy Meal® toy?": "Base",
    "Anthropologists have recently discovered a primitive tribe that worships _.": "Base",
    "It's a pity that kids these days are all getting involved with _.": "Base",
    "During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of _.": "Base",
    "Alternative medicine is now embracing the curative powers of _.": "Base",
//  "And the Academy Award for _ goes to _.": "Base",
    "What's that sound?": "Base",
    "What ended my last relationship?": "Base",
    "MTV's new reality show features eight washed-up celebrities living with _.": "Base",
    "I drink to forget _.": "Base",
    "I'm sorry professor, but I couldn't complete my homework because of _.": "Base",
    "What is Batman's guilty pleasure?": "Base",
    "This is the way the world ends \n This is the way the world ends \n Not with a bang but with _.": "Base",
    "What's a girl's best friend?": "Base",
    "TSA guidelines now prohibit _ on airplanes.": "Base",
    "_. That's how I want to die.": "Base",
//  "For my next trick, I will pull _ out of _.": "Base",
    "In the new Disney Channel Original Movie, Hannah Montana struggles with _ for the first time.": "Base",
    "_ is a slippery slope that leads to _.": "Base",
    "What does Dick Cheney prefer?": "Base",
    "Dear Abby, I'm having some trouble with _ and would like your advice.": "Base",
    "Instead of coal, Santa now gives the bad children _.": "Base",
    "What's the most emo?": "Base",
    "In 1,000 years when paper money is but a distant memory, _ will be our currency.": "Base",
    "What's the next superhero/sidekick duo?": "Base",
//  "In M. Night Shyamalan's new movie, Bruce Willis discovers that _ had really been _ all along.": "Base",
    "A romantic, candlelit dinner would be incomplete without _.": "Base",
    "_. Becha can't have just one!": "Base",
    "White people like _.": "Base",
    "_. High five, bro.": "Base",
    "Next from J.K. Rowling: Harry Potter and the Chamber of _.": "Base",
    "BILLY MAYS HERE FOR _.": "Base",
    "In a world ravaged by _, our only solace is _.": "Base",
    "War! What is it good for?": "Base",
//  "During sex, I like to think about _.": "Base",
    "What are my parents hiding from me?": "Base",
    "What will always get you laid?": "Base",
    "In L.A. County Jail, word is you can trade 200 cigarettes for _.": "Base",
    "What did I bring back from Mexico?": "Base",
    "What don't you want to find in your Chinese food?": "Base",
    "What will I bring back in time to convince people that I am a powerful wizard?": "Base",
    "How am I maintaining my relationship status?": "Base",
    "_. It's a trap!": "Base",
    "Coming to Broadway this season, _: The Musical.": "Base",
    "While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on _.": "Base",
    "After the earthquake, Sean Penn brought _ to the people of Haiti.": "Base",
    "Next on ESPN2, the World Series of _.": "Base",
//  "Step 1: _. Step 2: _. Step 3: Profit.": "Base",
//  "Rumor has it that Vladimir Putin's favorite dish is _ stuffed with _.": "Base",
    "But before I kill you, Mr. Bond, I must show you _.": "Base",
    "What gives me uncontrollable gas?": "Base",
    "What do old people smell like?": "Base",
    "The class field trip was completely ruined by _.": "Base",
    "When Pharaoh remained unmoved, Moses called down a Plague of _.": "Base",
    "What's my secret power?": "Base",
    "What's there a ton of in heaven?": "Base",
    "What would grandma find disturbing, yet oddly charming?": "Base",
//  "I never truly understood _ until I encountered _.": "Base",
    "What did the U.S. airdrop to the children of Afghanistan?": "Base",
    "What helps Obama unwind?": "Base",
    "What did Vin Diesel eat for dinner?": "Base",
    "_: good to the last drop.": "Base",
    "Why am I sticky?": "Base",
    "What gets better with age?": "Base",
    "_: kid-tested, mother-approved.": "Base",
    "What's the crustiest?": "Base",
    "What's Teach for America using to inspire inner city students to succeed?": "Base",
    "Studies show that lab rats navigate mazes 50% faster after being exposed to _.": "Base",
    "Life for American Indians was forever changed when the White Man introduced them to _.": "Base",
    "Make a haiku.": "Base",
    "I do not know with what weapons World War III will be fought, but World War IV will be fought with _.": "Base",
    "Why do I hurt all over?": "Base",
    "What am I giving up for Lent?": "Base",
    "In Michael Jackson's final moments, he thought about _.": "Base",
    "In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on _.": "Base",
    "When I am President of the United States, I will create the Department of _.": "Base",
//  "Lifetime® presents _, the story of _.": "Base",
    "When I am a billionaire, I shall erect a 50-foot statue to commemorate _.": "Base",
    "When I was tripping on acid, _ turned into _.": "Base",
//  "That's right, I killed _. How, you ask? _.": "Base",
    "What's my anti-drug?": "Base",
//  "_ plus _ equals _.": "Base",
    "What never fails to liven up the party?": "Base",
    "What's the new fad diet?": "Base",
    "Major League Baseball has banned _ for giving players an unfair advantage.": "Base",
    /*
     *
     * BLACK CARDS
     * Tech
     *
     */
    "Because of my investment in Bitcoin, soon I'll be able to afford _.": "Tech",
    "What’s my startup disrupting?": "Tech",
    "At my company, they feed us fresh _ at every meal.": "Tech",
    "It’s not a tech bubble, it’s _.": "Tech",
    "The inspiration for my startup.": "Tech",
    "My company was just acquired by _.": "Tech",
    "Thanks to the sharing economy, I can now make money renting out my _.": "Tech",
    "How can we monetize _?": "Tech",
    "Facebook just bought _.": "Tech",
    "I made an app that’s like _, but for _.": "Tech",
    "It’s hard being _ in tech.": "Tech",
    "Silicon Valley is full of _.": "Tech",
    /*
     *
     * BLACK CARDS
     * Furry
     *
     */
    "_ are so goddamn cool.": "Furry",
    "Once I started roleplaying _, it was all downhill from there.": "Furry",
    "It's difficult to explain to friends and family why I know so much about _.": "Furry",
    "It all started with _.": "Furry",
    "My secret tumblr account where I post nothing but _.": "Furry",
    "The most recent item in my search history.": "Furry",
    "In my past life, I was _.": "Furry",
    "I'm about 50% _.": "Furry",
    "Most cats are _.": "Furry"

  })
}(window.app)
